spring:
  application:
    name: itoken-eureka

server:
  port: 8761

eureka:
  instance:
    hostname: host
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.171.135:8761/eureka/,http://192.168.171.135:8861/eureka/,http://192.168.171.135:8961/eureka/
