spring:
  application:
    name: itoken-zipkin
  boot:
    admin:
      client:
        url: http://106.14.133.27:8084
  zipkin:
    base-url: http://106.14.133.27:9411

server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://106.14.133.27:8761/eureka/,http://106.14.133.27:8861/eureka/,http://106.14.133.27:8961/eureka/
