spring:
  application:
    name: itoken-eureka

---
server:
  port: 8761

eureka:
  instance:
    hostname: 106.14.133.27
    appname: itoken-eureka
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/,http://${eureka.instance.hostname}:8861/eureka/,http://${eureka.instance.hostname}:8961/eureka/

---
server:
  port: 8861

eureka:
  instance:
    hostname: 106.14.133.27
    appname: itoken-eureka
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/,http://${eureka.instance.hostname}:8861/eureka/,http://${eureka.instance.hostname}:8961/eureka/

---
server:
  port: 8961

eureka:
  instance:
    hostname: 106.14.133.27
    appname: itoken-eureka
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/,http://${eureka.instance.hostname}:8861/eureka/,http://${eureka.instance.hostname}:8961/eureka/
