spring:
  application:
    name: itoken-service-admin
  boot:
    admin:
      client:
        url: http://192.168.171.135:8084
  zipkin:
    base-url: http://192.168.171.135:9411
  datasource:
    druid:
      url: jdbc:mysql://47.107.135.196:3306/itoken-service-admin?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: job
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8501

mybatis:
  type-aliases-package: com.itoken.service.admin.domain
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://106.14.133.27:8761/eureka/,http://106.14.133.27:8861/eureka/,http://106.14.133.27:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info